# Generated by Django 4.1 on 2022-08-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('club_name', models.CharField(max_length=50, unique=True)),
                ('competition_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=3, max_digits=5)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isabella.competition')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isabella.temporada')),
            ],
        ),
    ]
