# Generated by Django 4.1 on 2022-08-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isabella', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='note',
            new_name='competition_note',
        ),
    ]
