# Generated by Django 4.1 on 2022-08-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isabella', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('-competition_date',)},
        ),
        migrations.AlterField(
            model_name='note',
            name='temporada',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='isabella.temporada'),
        ),
    ]
